In [1]:
import pandas as pd
import numpy as np
import datetime
from sklearn import svm
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [2]:
csv_path = 'file:///Users/Stefan/Downloads/video_game_sales.csv'
project_data = pd.read_csv(csv_path)
csv_path1 = 'file:///Users/Stefan/Desktop/updatedrealeaseyear.csv'
release_date = pd.read_csv(csv_path1)
release_date = release_date[release_date['Year'] != 'N/A  ']

In [3]:
df1 = project_data.iloc[:,10].mul(1000000)
df2 = pd.DataFrame(df1, dtype=int)
del project_data['Global_Sales']
final_data = pd.merge(project_data, df2, left_index=True, right_index=True)
final_data.head()
# converting the global sales value into the millions and updating the dtype to millions

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82740000
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40240000
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35820000
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33000000
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31370000

In [4]:
final_data.update(release_date)
final_data['Year'] = pd.to_datetime(final_data['Year'])
final_data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006-11-19,Sports,Nintendo,41.49,29.02,3.77,8.46,82740000
1,2,Super Mario Bros.,NES,1985-10-18,Platform,Nintendo,29.08,3.58,6.81,0.77,40240000
2,3,Mario Kart Wii,Wii,2008-04-27,Racing,Nintendo,15.85,12.88,3.79,3.31,35820000
3,4,Wii Sports Resort,Wii,2009-07-26,Sports,Nintendo,15.75,11.01,3.28,2.96,33000000
4,5,Pokemon Red/Pokemon Blue,GB,1998-09-30,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31370000

In [10]:
date1 = datetime.datetime(2013, 12, 31)
date2 = datetime.datetime(2005, 1, 1)
df = (final_data['Year'] <= date1) & (final_data['Year'] >= date2)
training_set = final_data.loc[df]

In [11]:
qf = training_set['Platform'].value_counts()
qf = pd.DataFrame(qf)
qf.to_dict()
training_set.replace(qf, inplace=True)

qf1 = training_set['Publisher'].value_counts()
qf1 = pd.DataFrame(qf1)
qf1.to_dict()
training_set.replace(qf1, inplace=True)

qf2 = training_set['Genre'].value_counts()
qf2 = pd.DataFrame(qf2)
qf2.to_dict()
training_set.replace(qf2, inplace=True)

training_set

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,709,2006-11-19,1243,340.0,41.49,29.02,3.77,8.46,82740000
2,3,Mario Kart Wii,709,2008-04-27,652,340.0,15.85,12.88,3.79,3.31,35820000
3,4,Wii Sports Resort,709,2009-07-26,1243,340.0,15.75,11.01,3.28,2.96,33000000
6,7,New Super Mario Bros.,1180,2006-05-15,455,340.0,11.38,9.23,6.50,2.90,30010000
7,8,Wii Play,709,2007-02-12,922,340.0,14.03,9.20,2.93,2.85,29020000
8,9,New Super Mario Bros. Wii,709,2009-11-15,455,340.0,14.59,7.06,4.70,2.26,28620000
10,11,Nintendogs,1180,2005-08-23,443,340.0,9.07,11.00,1.93,2.75,24760000
11,12,Mario Kart DS,1180,2005-11-14,652,340.0,9.81,7.57,4.13,1.92,23420000
13,14,Wii Fit,709,2008-05-21,1243,340.0,8.94,8.03,3.60,2.15,22720000
14,15,Wii Fit Plus,709,2010-11-04,1243,340.0,9.09,8.59,2.53,1.79,22000000
15,16,Kinect Adventures!,641,2009-10-04,922,112.0,14.97,4.94,0.24,1.67,21820000
18,19,Super Mario World,108,2013-09-17,455,340.0,12.78,3.75,3.54,0.55,20610000
19,20,Brain Age: Train Your Brain in Minutes a Day,1180,2006-04-17,922,340.0,4.75,9.26,4.16,2.05,20220000
21,22,Super Mario Land,48,2007-04-28,455,340.0,10.83,2.71,4.18,0.42,18140000
25,26,Pokemon Ruby/Pokemon Sapphire,430,2013-10-12,780,340.0,6.06,3.90,5.38,0.50,15850000
26,27,Pokemon Black/Pokemon White,1180,2013-09-17,780,340.0,5.57,3.28,5.65,0.82,15320000
28,29,Gran Turismo 3: A-Spec,1149,2007-08-20,652,368.0,6.85,5.09,1.87,1.16,14980000
29,30,Call of Duty: Modern Warfare 3,641,2011-03-06,693,501.0,9.03,4.28,0.13,1.32,14760000
30,31,Pok̩mon Yellow: Special Pikachu Edition,48,2011-12-04,780,340.0,5.89,5.04,3.12,0.59,14640000
34,35,Call of Duty: Black Ops II,711,2011-11-08,693,501.0,4.99,5.88,0.65,2.52,14030000
35,36,Call of Duty: Black Ops II,641,2010-11-09,693,501.0,8.25,4.30,0.07,1.12,13730000
37,38,Call of Duty: Modern Warfare 3,711,2012-11-13,693,501.0,5.54,5.82,0.49,1.62,13460000
38,39,Grand Theft Auto III,1149,2012-11-13,1743,233.0,6.99,4.51,0.30,1.30,13100000
39,40,Super Smash Bros. Brawl,709,2009-11-10,438,340.0,6.75,2.61,2.66,1.02,13040000
40,41,Call of Duty: Black Ops,711,2011-11-08,693,501.0,5.98,4.44,0.48,1.83,12730000
43,44,Halo 3,641,2008-03-09,693,112.0,7.97,2.83,0.13,1.21,12140000
45,46,Pokemon HeartGold/Pokemon SoulSilver,1180,2010-11-09,1743,340.0,4.40,2.77,3.96,0.77,11900000
46,47,Super Mario 64,154,2005-12-05,455,340.0,6.91,2.85,1.91,0.23,11890000
47,48,Gran Turismo 4,1149,2007-09-25,652,368.0,3.01,0.01,1.10,7.53,11660000
49,50,Pokemon Omega Ruby/Pokemon Alpha Sapphire,298,2010-03-14,780,340.0,4.23,3.37,3.08,0.65,11330000
...,...,...,...,...,...,...,...,...,...,...,...
16552,16555,Mahou Sensei Negima!? Neo-Pactio Fight!!,709,2006-01-26,438,35.0,0.00,0.00,0.01,0.00,10000
16554,16557,Psychic Detective,618,2011-11-10,742,669.0,0.01,0.00,0.00,0.00,10000
16555,16558,Codename: Panzers Complete Collection,506,2005-04-04,359,18.0,0.00,0.01,0.00,0.00,10000
16556,16559,Super Robot Taisen: Original Generation,430,2010-01-28,780,42.0,0.01,0.00,0.00,0.00,10000
16557,16560,Dramatical Murder Re:code,225,2011-08-19,742,1.0,0.00,0.00,0.01,0.00,10000
16559,16562,Sugar + Spice! Anoko no Suteki na Nanimokamo,1149,2006-03-29,742,22.0,0.00,0.00,0.01,0.00,10000
16560,16563,Hanasaku Manimani,225,2011-08-04,742,35.0,0.00,0.00,0.01,0.00,10000
16561,16564,Kanokon: Esuii,1149,2006-09-28,742,35.0,0.00,0.00,0.01,0.00,10000
16562,16565,Mighty No. 9,111,2008-08-25,455,57.0,0.01,0.00,0.00,0.00,10000
16563,16566,Mortal Kombat: Deadly Alliance,430,2007-05-04,438,105.0,0.01,0.00,0.00,0.00,10000
16565,16568,Teslagrad,225,2011-11-22,455,1.0,0.00,0.01,0.00,0.00,10000
16567,16570,Fujiko F. Fujio Characters: Great Assembly! Sl...,298,2013-05-21,1743,480.0,0.00,0.00,0.01,0.00,10000
16568,16571,XI Coliseum,637,2008-01-10,317,368.0,0.00,0.00,0.01,0.00,10000
16571,16574,Grisaia no Kajitsu: La Fruit de la Grisaia,637,2012-02-23,742,21.0,0.00,0.00,0.01,0.00,10000
16572,16575,Scarlett: Nichijou no Kyoukaisen,1149,2011-04-28,742,26.0,0.00,0.00,0.01,0.00,10000
16573,16576,Mini Desktop Racing,709,2005-08-02,652,5.0,0.01,0.00,0.00,0.00,10000
16575,16578,Neo Angelique Special,637,2010-11-05,742,192.0,0.00,0.00,0.01,0.00,10000
16576,16579,Rugby Challenge 3,111,2013-07-25,1243,4.0,0.00,0.01,0.00,0.00,10000
16578,16581,Outdoors Unleashed: Africa 3D,298,2012-08-23,1243,12.0,0.01,0.00,0.00,0.00,10000
16579,16582,PGA European Tour,154,2008-10-10,1243,29.0,0.01,0.00,0.00,0.00,10000
16580,16583,Real Rode,1149,2009-10-31,742,26.0,0.00,0.00,0.01,0.00,10000
16582,16585,Planet Monsters,430,2012-05-24,1743,15.0,0.01,0.00,0.00,0.00,10000
16583,16586,Carmageddon 64,154,2006-08-14,1743,30.0,0.01,0.00,0.00,0.00,10000
16586,16589,Secret Files 2: Puritas Cordis,1180,2008-06-11,742,57.0,0.00,0.01,0.00,0.00,10000
16588,16591,Mega Brain Boost,1180,2008-03-04,317,48.0,0.01,0.00,0.00,0.00,10000
16592,16595,Plushees,1180,2011-03-31,443,24.0,0.01,0.00,0.00,0.00,10000
16593,16596,Woody Woodpecker in Crazy Castle 5,430,2008-10-16,455,9.0,0.01,0.00,0.00,0.00,10000
16594,16597,Men in Black II: Alien Escape,307,2009-09-22,693,29.0,0.01,0.00,0.00,0.00,10000
16595,16598,SCORE International Baja 1000: The Official Game,1149,2012-04-13,652,501.0,0.00,0.00,0.00,0.00,10000
16596,16599,Know How 2,1180,2013-08-29,317,4.0,0.00,0.01,0.00,0.00,10000

In [8]:
date3 = datetime.datetime(2014, 12, 31)
date4 = datetime.datetime(2014, 1, 1)
df = (final_data['Year'] <= date3) & (final_data['Year'] >= date4)
test_set1 = final_data.loc[df]

date5 = datetime.datetime(2015, 12, 31)
date6 = datetime.datetime(2015, 1, 1)
df = (final_data['Year'] <= date5) & (final_data['Year'] >= date6)
test_set2 = final_data.loc[df]

date7 = datetime.datetime(2016, 12, 31)
date8 = datetime.datetime(2016, 1, 1)
df = (final_data['Year'] <= date7) & (final_data['Year'] >= date8)
test_set3 = final_data.loc[df]


date9 = datetime.datetime(2017, 12, 31)
date10 = datetime.datetime(2017, 1, 1)
df = (final_data['Year'] <= date9) & (final_data['Year'] >= date10)
test_set4 = final_data.loc[df]

In [9]:
#Defining Independent and Dependent Variables
X = training_set.values[:,[2,3,4,5]]
Y = training_set.values[:, 10]
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = .1, random_state = 70)